// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2471.BunnyBot2015.subsystems;

import org.usfirst.frc2471.BunnyBot2015.RobotMap;
import org.usfirst.frc2471.BunnyBot2015.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController speedController5 = RobotMap.driveSpeedController5;
    SpeedController speedController6 = RobotMap.driveSpeedController6;
    Encoder quadratureEncoder1 = RobotMap.driveQuadratureEncoder1;
    Encoder quadratureEncoder2 = RobotMap.driveQuadratureEncoder2;
    SpeedController speedController1 = RobotMap.driveSpeedController1;
    SpeedController speedController2 = RobotMap.driveSpeedController2;
    SpeedController speedController3 = RobotMap.driveSpeedController3;
    SpeedController speedController4 = RobotMap.driveSpeedController4;
    RobotDrive robotDrive41 = RobotMap.driveRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

